DROP TABLE IF EXISTS USERS;
CREATE TABLE IF NOT EXISTS USERS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  LOGIN VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  ROLES VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS CITIES;
CREATE TABLE IF NOT EXISTS CITIES (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS MUSEUMS;
CREATE TABLE IF NOT EXISTS MUSEUMS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  CITY_ID INTEGER NOT NULL,
  DESCRIPTION VARCHAR(2048),
  ADDRESS VARCHAR(512) NOT NULL,
  PHONE VARCHAR(20),
  IMAGE VARCHAR(255),
  EMAIL VARCHAR(255),
  ABOUT VARCHAR NOT NULL
);

DROP TABLE IF EXISTS MUSEUM_IMAGES;
CREATE TABLE IF NOT EXISTS MUSEUM_IMAGES (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  MUSEUM_ID INTEGER NOT NULL,
  DESCRIPTION VARCHAR(2048),
  SRC VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS EVENTS;
CREATE TABLE IF NOT EXISTS EVENTS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  CITY_ID INTEGER NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(2048),
  IMAGE VARCHAR(255),
  ABOUT VARCHAR NOT NULL,
  EVENT_TYPE VARCHAR(10) NOT NULL,
  START_TIME VARCHAR(255),
  FINISH_TIME VARCHAR(255)
);